# -*- coding: utf-8 -*-
"""Probando Carga inicial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxaD9kqNcRVSpplOyPWLjtFbGTJoMan4
"""

"""
=============================================================
  LMN Bicentenario — Sistema de Inventario (versión mejorada)
=============================================================
Mejoras aplicadas:
  - Separación de responsabilidades (datos / lógica / UI)
  - Backup automático antes de guardar
  - Validación de stock disponible antes de registrar salida
  - Validación de tipo de movimiento
  - Guardado en dos pasos para evitar race condition
  - Excepciones explícitas (sin except vacío)
  - Fechas guardadas como datetime
  - Carga única del Excel por sesión
  - Validación de cantidad con reintento
  - Constante HEADER_ROW para fácil ajuste
  - Consulta de stock por código o nombre (opción 4)
  - Acción directa sobre el insumo consultado (ingreso/salida)
"""

import shutil
import pandas as pd
from datetime import datetime
from pathlib import Path
from google.colab import drive

# ─────────────────────────────────────────────
# CONFIGURACIÓN GLOBAL
# ─────────────────────────────────────────────
HEADER_ROW = 2          # Fila donde comienzan los datos en cada hoja (0-indexed: skiprows)
RUTA_EXCEL = '/content/drive/MyDrive/Inventario Marcha Blanca - corregido(1).xlsx'
DIR_BACKUP = '/content/drive/MyDrive/Backups_Inventario'


# ═════════════════════════════════════════════
# CAPA 1: ACCESO A DATOS (InventarioRepo)
# ═════════════════════════════════════════════

class InventarioRepo:
    """
    Responsabilidad única: leer y escribir el archivo Excel.
    No contiene lógica de negocio ni interacción con el usuario.
    """

    def __init__(self, ruta: str):
        self.ruta = ruta

    # ── Lectura ───────────────────────────────

    def cargar_hoja(self, nombre_hoja: str) -> pd.DataFrame:
        """Lee una hoja y devuelve un DataFrame limpio."""
        df = pd.read_excel(self.ruta, sheet_name=nombre_hoja, skiprows=HEADER_ROW)
        return self._limpiar(df)

    def cargar_insumos(self) -> pd.DataFrame:
        return self.cargar_hoja('Insumos')

    def cargar_sucursales(self) -> list:
        df = pd.read_excel(self.ruta, sheet_name='Sucursales', skiprows=HEADER_ROW)
        return df['Sucursal'].dropna().unique().tolist()

    def cargar_ingresos(self) -> pd.DataFrame:
        return self.cargar_hoja('Ingresos')

    def cargar_salidas(self) -> pd.DataFrame:
        return self.cargar_hoja('Salidas')

    # ── Escritura ─────────────────────────────

    def guardar_transaccion(self, df: pd.DataFrame, hoja: str):
        """Guarda la hoja de transacciones (Ingresos o Salidas)."""
        with pd.ExcelWriter(
            self.ruta, mode='a', engine='openpyxl', if_sheet_exists='replace'
        ) as writer:
            df.to_excel(writer, sheet_name=hoja, index=False, startrow=HEADER_ROW)

    def leer_archivo_inicial(self, ruta: str) -> pd.DataFrame:
        """
        Lee un Excel o CSV externo con el inventario inicial.
        Acepta: .xlsx, .xls, .csv
        Devuelve el DataFrame crudo para que el servicio lo valide.
        """
        ruta = ruta.strip().strip("'\"")
        ext = Path(ruta).suffix.lower()
        if ext == '.csv':
            df = pd.read_csv(ruta, dtype=str)
        elif ext in ('.xlsx', '.xls'):
            df = pd.read_excel(ruta, dtype=str)
        else:
            raise ValueError(f"Formato no soportado: '{ext}'. Use .xlsx, .xls o .csv")
        df.columns = df.columns.str.strip()
        return df

    def guardar_reportes(
        self,
        df_stock_lote: pd.DataFrame,
        df_stock_suc: pd.DataFrame,
        df_sin_lote: pd.DataFrame | None,
    ):
        """Guarda las tres hojas de reporte en una sola apertura del writer."""
        with pd.ExcelWriter(
            self.ruta, mode='a', engine='openpyxl', if_sheet_exists='replace'
        ) as writer:
            df_stock_suc.to_excel(
                writer, sheet_name='Stock por Sucursal', index=False, startrow=HEADER_ROW
            )
            df_stock_lote.to_excel(
                writer, sheet_name='Stock por Lote', index=False, startrow=HEADER_ROW
            )
            if df_sin_lote is not None and not df_sin_lote.empty:
                df_sin_lote.to_excel(
                    writer, sheet_name='Stock sin Lote ni Vencimiento',
                    index=False, startrow=HEADER_ROW
                )

    # ── Backup ────────────────────────────────

    def hacer_backup(self) -> str:
        """Copia el archivo Excel a la carpeta de backups. Devuelve la ruta del backup."""
        Path(DIR_BACKUP).mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        nombre_original = Path(self.ruta).stem
        destino = f"{DIR_BACKUP}/{nombre_original}_backup_{ts}.xlsx"
        shutil.copy2(self.ruta, destino)
        return destino

    # ── Utilidades privadas ───────────────────

    @staticmethod
    def _limpiar(df: pd.DataFrame) -> pd.DataFrame:
        """Normaliza tipos y elimina espacios en columnas clave."""
        if df.empty:
            return df
        for col in ('Código', 'Lote'):
            if col in df.columns:
                df[col] = df[col].astype(str).str.strip().str.upper()
        if 'Nombre del insumo' in df.columns:
            df['Nombre del insumo'] = df['Nombre del insumo'].astype(str).str.strip()
        if 'Cantidad' in df.columns:
            df['Cantidad'] = pd.to_numeric(df['Cantidad'], errors='coerce').fillna(0)
        return df


# ═════════════════════════════════════════════
# CAPA 2: LÓGICA DE NEGOCIO (StockService)
# ═════════════════════════════════════════════

class StockService:
    """
    Responsabilidad única: cálculos de stock y construcción de reportes.
    Recibe los DataFrames ya cargados; no accede al archivo directamente.
    """

    def __init__(self, repo: InventarioRepo):
        self.repo = repo

    # ── Consultas de stock ────────────────────

    def stock_por_lote(self, codigo: str, df_ing: pd.DataFrame, df_sal: pd.DataFrame) -> pd.DataFrame:
        """
        Devuelve un DataFrame con el stock disponible por lote para un código dado.
        Incluye solo lotes con stock > 0.
        """
        codigo = codigo.strip().upper()
        ing = df_ing[df_ing['Código'] == codigo].copy()
        sal = df_sal[df_sal['Código'] == codigo].copy()

        if ing.empty:
            return pd.DataFrame()

        resumen_ing = (
            ing.groupby(['Lote', 'Fecha de caducidad'])['Cantidad']
            .sum()
            .reset_index()
        )

        if not sal.empty:
            resumen_sal = (
                sal.groupby(['Lote', 'Fecha de caducidad asociada'])['Cantidad']
                .sum()
                .reset_index()
            )
            resumen_sal.columns = ['Lote', 'Fecha de caducidad', 'Cant_Salida']
            df_lotes = resumen_ing.merge(
                resumen_sal, on=['Lote', 'Fecha de caducidad'], how='left'
            ).fillna(0)
            df_lotes['Disponible'] = df_lotes['Cantidad'] - df_lotes['Cant_Salida']
        else:
            df_lotes = resumen_ing.copy()
            df_lotes['Disponible'] = df_lotes['Cantidad']

        return df_lotes[df_lotes['Disponible'] > 0].reset_index(drop=True)

    def hay_stock_suficiente(
        self, codigo: str, lote: str, cantidad: float,
        df_ing: pd.DataFrame, df_sal: pd.DataFrame
    ) -> bool:
        """Valida que exista stock suficiente para la cantidad solicitada."""
        lotes = self.stock_por_lote(codigo, df_ing, df_sal)
        if lotes.empty:
            return False
        fila = lotes[lotes['Lote'] == lote]
        if fila.empty:
            return False
        return float(fila.iloc[0]['Disponible']) >= cantidad

    # ── Construcción de reportes ──────────────

    def construir_stock_por_lote(
        self, df_ing: pd.DataFrame, df_sal: pd.DataFrame
    ) -> pd.DataFrame:
        ing_ag = df_ing.groupby(
            ['Código', 'Nombre del insumo', 'Lote', 'Fecha de caducidad']
        )['Cantidad'].sum().reset_index()

        sal_ag = df_sal.groupby(
            ['Código', 'Lote', 'Fecha de caducidad asociada']
        )['Cantidad'].sum().reset_index()
        sal_ag.columns = ['Código', 'Lote', 'Fecha de caducidad', 'Cant_Salida']

        df = ing_ag.merge(sal_ag, on=['Código', 'Lote', 'Fecha de caducidad'], how='left').fillna(0)
        df['Stock disponible'] = df['Cantidad'] - df['Cant_Salida']

        df = df.rename(columns={'Cantidad': 'Ingresos', 'Cant_Salida': 'Salidas'})
        return df[['Código', 'Nombre del insumo', 'Lote', 'Fecha de caducidad',
                   'Ingresos', 'Salidas', 'Stock disponible']]

    def construir_stock_por_sucursal(
        self, df_ing: pd.DataFrame, df_sal: pd.DataFrame,
        df_insumos: pd.DataFrame, lista_suc: list
    ) -> pd.DataFrame:
        """
        Lógica de columnas:
          - Total Ingresos (BC)     : todo lo que ingresó a Bodega Central
          - Usado en BC             : salidas cuyo destino es 'Bodega Central' (consumo interno)
          - Enviado a <Sucursal>    : salidas cuyo destino es esa sucursal
          - Stock Disponible (BC)   : Total Ingresos − Usado en BC − sum(Enviado a sucursales)
          - STOCK TOTAL             : Stock BC + sum(Enviado a sucursales)
                                      (lo usado en BC NO cuenta como stock, ya fue consumido)
        """
        todos_los_insumos = df_insumos['Nombre del insumo'].unique()

        # ── Totales de ingreso ────────────────────────────────────────────
        total_ing = (
            df_ing.groupby('Nombre del insumo')['Cantidad']
            .sum()
            .reindex(todos_los_insumos, fill_value=0)
        )

        # ── Matriz de salidas por destino ─────────────────────────────────
        if not df_sal.empty and 'Destino' in df_sal.columns:
            matriz = (
                df_sal.groupby(['Nombre del insumo', 'Destino'])['Cantidad']
                .sum()
                .unstack(fill_value=0)
                .reindex(todos_los_insumos, fill_value=0)
            )
        else:
            matriz = pd.DataFrame(0, index=todos_los_insumos, columns=[])

        # ── Construcción del reporte ──────────────────────────────────────
        reporte = pd.DataFrame(index=todos_los_insumos)
        reporte.index.name = 'Nombre del insumo'

        reporte['Usado en BC'] = (
            matriz['Bodega Central'] if 'Bodega Central' in matriz.columns else 0
        )

        sucursales_externas = [s for s in lista_suc if s != 'Bodega Central']
        for suc in sucursales_externas:
            reporte[f'Enviado a {suc}'] = (
                matriz[suc] if suc in matriz.columns else 0
            )

        destinos_extra = [
            d for d in matriz.columns
            if d != 'Bodega Central' and d not in sucursales_externas
        ]
        for dest in destinos_extra:
            reporte[f'Enviado a {dest}'] = matriz[dest]

        cols_enviado = [c for c in reporte.columns if c.startswith('Enviado a')]
        total_enviado = reporte[cols_enviado].sum(axis=1) if cols_enviado else 0

        reporte['Stock Disponible (Bodega Central)'] = (
            total_ing - reporte['Usado en BC'] - total_enviado
        )

        reporte['STOCK TOTAL'] = reporte['Stock Disponible (Bodega Central)'] + total_enviado

        cols_orden = (
            ['Stock Disponible (Bodega Central)', 'Usado en BC']
            + cols_enviado
            + ['STOCK TOTAL']
        )
        return (
            reporte[cols_orden]
            .fillna(0)
            .reset_index()
        )

    def validar_e_importar_inicial(
        self, df_raw: pd.DataFrame, df_insumos: pd.DataFrame
    ) -> tuple[pd.DataFrame, list[str]]:
        """
        Valida el DataFrame crudo del inventario inicial y lo convierte
        en filas listas para agregar a la hoja 'Ingresos'.

        Columnas requeridas en el archivo externo:
            Código | Cantidad
        Columnas opcionales:
            Lote | Fecha de caducidad (DD-MM-AAAA) | Proveedor | Observación
        """
        COLS_REQUERIDAS = {'Código', 'Cantidad'}
        faltantes = COLS_REQUERIDAS - set(df_raw.columns)
        if faltantes:
            raise ValueError(
                f"Al archivo le faltan las columnas obligatorias: {faltantes}\n"
                f"Columnas detectadas: {list(df_raw.columns)}"
            )

        codigos_validos = set(df_insumos['Código'].astype(str).str.strip().str.upper())
        nombre_por_codigo = (
            df_insumos.set_index('Código')['Nombre del insumo'].to_dict()
        )

        filas_ok = []
        errores  = []

        for i, row in df_raw.iterrows():
            num_fila = i + 1

            cod = str(row.get('Código', '')).strip().upper()
            if not cod or cod == 'NAN':
                errores.append(f"Fila {num_fila}: código vacío — omitida.")
                continue
            if cod not in codigos_validos:
                errores.append(
                    f"Fila {num_fila}: código '{cod}' no existe en la hoja Insumos — omitida."
                )
                continue

            try:
                cant = float(str(row.get('Cantidad', '')).replace(',', '.'))
                if cant <= 0:
                    raise ValueError
            except ValueError:
                errores.append(
                    f"Fila {num_fila} ({cod}): cantidad inválida "
                    f"'{row.get('Cantidad')}' — omitida."
                )
                continue

            lote_raw = str(row.get('Lote', '')).strip().upper()
            lote = lote_raw if lote_raw and lote_raw != 'NAN' else 'N/A'

            venc_raw = str(row.get('Fecha de caducidad', '')).strip()
            if venc_raw and venc_raw.upper() != 'NAN':
                try:
                    venc = datetime.strptime(venc_raw, "%d-%m-%Y")
                except ValueError:
                    errores.append(
                        f"Fila {num_fila} ({cod}): fecha '{venc_raw}' no tiene "
                        f"formato DD-MM-AAAA — se guardará como 'S/V'."
                    )
                    venc = 'S/V'
            else:
                venc = 'S/V'

            proveedor = str(row.get('Proveedor', '')).strip()
            proveedor = proveedor if proveedor and proveedor.upper() != 'NAN' else ''

            obs_raw = str(row.get('Observación', '')).strip()
            obs = obs_raw if obs_raw and obs_raw.upper() != 'NAN' else 'Inventario inicial'

            filas_ok.append({
                'Fecha'              : datetime.now(),
                'Código'             : cod,
                'Nombre del insumo'  : nombre_por_codigo[cod],
                'Lote'               : lote,
                'Cantidad'           : cant,
                'Fecha de caducidad' : venc,
                'Proveedor'          : proveedor,
                'Observación'        : obs,
            })

        return pd.DataFrame(filas_ok), errores

    def construir_stock_sin_lote(
        self, df_ing: pd.DataFrame, df_sal: pd.DataFrame,
        lista_suc: list
    ) -> pd.DataFrame | None:
        ing_sin = df_ing[df_ing['Lote'].isin(['N/A', ''])].copy()
        sal_sin = df_sal[df_sal['Lote'].isin(['N/A', ''])].copy()

        if ing_sin.empty:
            return None

        total_ing = ing_sin.groupby('Nombre del insumo')['Cantidad'].sum()
        total_sal = sal_sin.groupby('Nombre del insumo')['Cantidad'].sum()
        stock_bc = (total_ing - total_sal).fillna(total_ing)

        matriz = sal_sin.groupby(
            ['Nombre del insumo', 'Destino']
        )['Cantidad'].sum().unstack(fill_value=0)

        reporte = pd.DataFrame(index=ing_sin['Nombre del insumo'].unique())
        reporte['Stock Disponible (Bodega Central)'] = stock_bc

        for s in lista_suc:
            if s != 'Bodega Central':
                reporte[f'Enviado a {s}'] = matriz[s] if s in matriz.columns else 0

        reporte['STOCK TOTAL SIN LOTE'] = reporte.sum(axis=1)
        return reporte.fillna(0).reset_index().rename(columns={'index': 'Nombre del insumo'})


# ═════════════════════════════════════════════
# CAPA 3: INTERFAZ DE USUARIO (MenuConsola)
# ═════════════════════════════════════════════

class MenuConsola:
    """
    Responsabilidad única: interacción con el usuario por consola.
    Delega toda la lógica al StockService y toda la persistencia al InventarioRepo.
    """

    def __init__(self, repo: InventarioRepo, servicio: StockService):
        self.repo = repo
        self.servicio = servicio
        # Carga única de datos al iniciar la sesión
        self.df_insumos = repo.cargar_insumos()
        self.lista_suc = repo.cargar_sucursales()
        self.df_ing = repo.cargar_ingresos()
        self.df_sal = repo.cargar_salidas()

    # ── Punto de entrada ──────────────────────

    def ejecutar(self):
        print("\n══════════════════════════════════════════")
        print("   LMN Bicentenario — Registro de Inventario")
        print("══════════════════════════════════════════")

        while True:
            tipo = self._pedir_tipo_movimiento()
            if tipo is None:
                print("🚫 Sesión finalizada.")
                break

            if tipo == '3':
                self._flujo_carga_inicial()
            elif tipo == '4':
                self._flujo_consulta_stock()
            else:
                self._ejecutar_operacion(tipo)

            # ── Preguntar si continuar ────────────────
            print("\n──────────────────────────────────────────")
            continuar = input("¿Desea realizar otra operación? (S/N): ").strip().upper()
            if continuar != 'S':
                print("\n👋 ¡Hasta luego!")
                break

            # Recargar datos para reflejar cambios guardados
            self.df_ing = self.repo.cargar_ingresos()
            self.df_sal = self.repo.cargar_salidas()
            print("\n🔄 Datos actualizados. Iniciando nueva operación...")

    def _ejecutar_operacion(self, tipo: str):
        """Gestiona el ciclo completo de una única operación (ingreso o salida)."""
        nombre_hoja = 'Ingresos' if tipo == '1' else 'Salidas'
        df_actual = self.df_ing.copy() if tipo == '1' else self.df_sal.copy()
        nuevas_filas = []

        while True:
            cod = input("\nCódigo del insumo (o 'fin' para guardar): ").strip().upper()
            if cod == 'FIN':
                break

            fila = self._registrar_producto(cod, tipo)
            if fila is not None:
                nuevas_filas.append(fila)
                print("✅ Registro agregado temporalmente.")

        if not nuevas_filas:
            print("\nℹ️ No hay movimientos para registrar.")
            return

        df_actual = pd.concat(
            [df_actual, pd.DataFrame(nuevas_filas)], ignore_index=True
        )
        self._guardar(df_actual, nombre_hoja)

    # ── Flujo de consulta de stock ────────────

    def _flujo_consulta_stock(self):
        """
        Permite buscar un insumo por código exacto o nombre parcial,
        muestra el stock disponible por lote y ofrece registrar un
        ingreso o salida del mismo producto sin volver al menú principal.
        """
        print("\n╔══════════════════════════════════════════╗")
        print("║           CONSULTA DE STOCK              ║")
        print("╚══════════════════════════════════════════╝")

        # ── Buscar insumo ──────────────────────────────────────────────────
        termino = input("Código o nombre del insumo: ").strip().upper()
        if not termino:
            print("⚠️  Búsqueda cancelada.")
            return

        # Busca por código exacto primero; si no hay coincidencia exacta,
        # amplía la búsqueda por nombre parcial (case-insensitive).
        mask = (
            (self.df_insumos['Código'] == termino) |
            (self.df_insumos['Nombre del insumo'].str.upper().str.contains(termino, na=False))
        )
        coincidencias = self.df_insumos[mask]

        if coincidencias.empty:
            print("❌ No se encontró ningún insumo con ese código o nombre.")
            return

        # Si hay más de un resultado, pide al usuario que elija
        if len(coincidencias) > 1:
            print("\nSe encontraron varios insumos:")
            for i, row in coincidencias.reset_index(drop=True).iterrows():
                print(f"  {i}) {row['Código']} — {row['Nombre del insumo']}")
            sel = input("Seleccione N° (o 'C' para cancelar): ").upper()
            if sel == 'C':
                return
            if not (sel.isdigit() and int(sel) < len(coincidencias)):
                print("❌ Selección inválida.")
                return
            fila_insumo = coincidencias.reset_index(drop=True).iloc[int(sel)]
        else:
            fila_insumo = coincidencias.iloc[0]

        cod = fila_insumo['Código']
        nom = fila_insumo['Nombre del insumo']

        # ── Mostrar stock por lote ─────────────────────────────────────────
        lotes = self.servicio.stock_por_lote(cod, self.df_ing, self.df_sal)

        print(f"\n📦 {nom}  (Código: {cod})")
        print("─" * 55)

        if lotes.empty:
            print("⚠️  Sin stock disponible.")
            stock_total = 0
        else:
            stock_total = 0
            for _, r in lotes.iterrows():
                fv = r['Fecha de caducidad']
                fv_str = fv.strftime('%d-%m-%Y') if hasattr(fv, 'strftime') else str(fv)
                print(
                    f"  Lote: {r['Lote']:<15}  "
                    f"Vence: {fv_str:<12}  "
                    f"Disponible: {int(r['Disponible'])}"
                )
                stock_total += r['Disponible']
            print("─" * 55)
            print(f"  {'TOTAL DISPONIBLE':<43} {int(stock_total)}")

        # ── Ofrecer acción directa sobre el mismo insumo ──────────────────
        print("\n¿Qué desea hacer con este insumo?")
        print("  1. Registrar INGRESO   2. Registrar SALIDA   C. Volver al menú")
        accion = input("Opción: ").strip().upper()

        if accion == '1':
            fila_nueva = self._flujo_ingreso(cod, nom)
            if fila_nueva:
                df_actual = pd.concat(
                    [self.df_ing, pd.DataFrame([fila_nueva])], ignore_index=True
                )
                self._guardar(df_actual, 'Ingresos')
        elif accion == '2':
            fila_nueva = self._flujo_salida(cod, nom)
            if fila_nueva:
                df_actual = pd.concat(
                    [self.df_sal, pd.DataFrame([fila_nueva])], ignore_index=True
                )
                self._guardar(df_actual, 'Salidas')

    # ── Flujo de registro de un producto ─────

    def _registrar_producto(self, cod: str, tipo: str) -> dict | None:
        """Orquesta el registro de un único producto. Devuelve la fila o None."""
        match = self.df_insumos[self.df_insumos['Código'] == cod]
        if match.empty:
            print("❌ Código no encontrado.")
            return None

        nom = match.iloc[0]['Nombre del insumo']
        print(f"📦 Producto: {nom}")

        try:
            if tipo == '2':
                return self._flujo_salida(cod, nom)
            else:
                return self._flujo_ingreso(cod, nom)
        except KeyboardInterrupt:
            print("\n⚠️ Registro interrumpido.")
            return None

    def _flujo_salida(self, cod: str, nom: str) -> dict | None:
        """Recoge los datos para una SALIDA."""
        lotes_disp = self.servicio.stock_por_lote(cod, self.df_ing, self.df_sal)
        if lotes_disp.empty:
            print("⚠️ No hay stock disponible de este producto.")
            return None

        # Selección de lote
        print("\nLotes disponibles:")
        for idx, r in lotes_disp.iterrows():
            fv = r['Fecha de caducidad']
            fv_str = fv.strftime('%d-%m-%Y') if hasattr(fv, 'strftime') else str(fv)
            print(f"  {idx}) Lote: {r['Lote']} | Vence: {fv_str} | Stock: {r['Disponible']}")

        sel = input("Seleccione N° de lote (o 'C' para cancelar): ").upper()
        if sel == 'C':
            return None
        if not (sel.isdigit() and int(sel) in lotes_disp.index):
            print("❌ Selección inválida.")
            return None

        lote = lotes_disp.loc[int(sel), 'Lote']
        venc = lotes_disp.loc[int(sel), 'Fecha de caducidad']
        stock_max = lotes_disp.loc[int(sel), 'Disponible']

        # Selección de destino
        print("\nDestinos:")
        for i, s in enumerate(self.lista_suc):
            print(f"  {i}) {s}")
        sel_s = input("Seleccione N° destino: ")
        if not (sel_s.isdigit() and int(sel_s) < len(self.lista_suc)):
            print("❌ Destino inválido.")
            return None
        dest = self.lista_suc[int(sel_s)]

        # Cantidad con validación de stock
        cant = self._pedir_cantidad(maximo=stock_max)
        if cant is None:
            return None

        obs = input("Observación: ")

        if not self._confirmar(nom, lote, cant):
            return None

        return {
            'Fecha': datetime.now(),
            'Código': cod,
            'Nombre del insumo': nom,
            'Lote': lote,
            'Cantidad': cant,
            'Fecha de caducidad asociada': venc,
            'Destino': dest,
            'Observación': obs,
        }

    def _flujo_ingreso(self, cod: str, nom: str) -> dict | None:
        """Recoge los datos para un INGRESO."""
        lote = input("Lote (Enter si no tiene): ").strip().upper() or "N/A"

        venc_in = input("Vencimiento (DD-MM-AAAA) o Enter si no aplica: ").strip()
        venc = self._parsear_fecha(venc_in)

        cant = self._pedir_cantidad()
        if cant is None:
            return None

        proveedor = input("Proveedor: ").strip()
        obs = input("Observación: ").strip()

        if not self._confirmar(nom, lote, cant):
            return None

        return {
            'Fecha': datetime.now(),
            'Código': cod,
            'Nombre del insumo': nom,
            'Lote': lote,
            'Cantidad': cant,
            'Fecha de caducidad': venc,
            'Proveedor': proveedor,
            'Observación': obs,
        }

    # ── Guardado final ────────────────────────

    def _guardar(self, df_actual: pd.DataFrame, nombre_hoja: str):
        if input("\n💾 ¿Guardar cambios en el Excel? (S/N): ").upper() != 'S':
            print("🚫 Operación cancelada por el usuario.")
            return

        # 1. Backup preventivo
        try:
            ruta_backup = self.repo.hacer_backup()
            print(f"📁 Backup creado: {ruta_backup}")
        except Exception as e:
            print(f"⚠️ No se pudo crear backup: {e}")
            if input("¿Continuar de todas formas? (S/N): ").upper() != 'S':
                return

        # 2. Guardar transacciones (primer ExcelWriter)
        try:
            self.repo.guardar_transaccion(df_actual, nombre_hoja)
            print(f"✅ Hoja '{nombre_hoja}' guardada.")
        except Exception as e:
            print(f"❌ Error al guardar transacciones: {e}")
            return

        # 3. Recargar datos frescos desde el archivo ya actualizado
        try:
            df_ing_nuevo = self.repo.cargar_ingresos()
            df_sal_nuevo = self.repo.cargar_salidas()
        except Exception as e:
            print(f"❌ Error al recargar datos para reportes: {e}")
            return

        # 4. Construir reportes
        df_stock_lote = self.servicio.construir_stock_por_lote(df_ing_nuevo, df_sal_nuevo)
        df_stock_suc = self.servicio.construir_stock_por_sucursal(
            df_ing_nuevo, df_sal_nuevo, self.df_insumos, self.lista_suc
        )
        df_sin_lote = self.servicio.construir_stock_sin_lote(
            df_ing_nuevo, df_sal_nuevo, self.lista_suc
        )

        # 5. Guardar reportes (segundo ExcelWriter, archivo ya cerrado)
        try:
            self.repo.guardar_reportes(df_stock_lote, df_stock_suc, df_sin_lote)
            print("✅ Hojas de reporte actualizadas.")
        except Exception as e:
            print(f"❌ Error al guardar reportes: {e}")
            return

        print("\n✨ ¡Excel actualizado con éxito en todas sus hojas!")

    # ── Carga masiva de inventario inicial ────

    def _flujo_carga_inicial(self):
        """
        Guía al usuario para importar un Excel/CSV como inventario inicial.
        Muestra un resumen de errores y pide confirmación antes de guardar.
        """
        print("\n╔══════════════════════════════════════════╗")
        print("║        CARGA DE INVENTARIO INICIAL       ║")
        print("╚══════════════════════════════════════════╝")
        print("El archivo debe tener al menos las columnas:")
        print("  • Código        (obligatorio)")
        print("  • Cantidad      (obligatorio)")
        print("  • Lote          (opcional — se usará N/A si falta)")
        print("  • Fecha de caducidad  (opcional — formato DD-MM-AAAA)")
        print("  • Proveedor     (opcional)")
        print("  • Observación   (opcional)\n")

        ruta = input("Ruta del archivo Excel/CSV: ").strip()
        if not ruta:
            print("⚠️ Operación cancelada.")
            return

        # 1. Leer archivo externo
        try:
            df_raw = self.repo.leer_archivo_inicial(ruta)
        except Exception as e:
            print(f"❌ No se pudo leer el archivo: {e}")
            return

        print(f"\n📄 Archivo leído: {len(df_raw)} filas encontradas.")

        # 2. Validar y convertir
        try:
            df_filas, errores = self.servicio.validar_e_importar_inicial(
                df_raw, self.df_insumos
            )
        except ValueError as e:
            print(f"❌ Error de estructura: {e}")
            return

        # 3. Mostrar resumen de errores
        if errores:
            print(f"\n⚠️  {len(errores)} filas con problemas (serán omitidas):")
            for err in errores:
                print(f"   → {err}")

        if df_filas.empty:
            print("\n❌ No hay filas válidas para importar. Revisa el archivo.")
            return

        print(f"\n✅ {len(df_filas)} filas válidas listas para importar.")
        print("\nVista previa (primeras 5 filas):")
        print(df_filas[['Código', 'Nombre del insumo', 'Lote', 'Cantidad']].head().to_string(index=False))

        # 4. Confirmar
        if input("\n¿Confirmar importación? (S/N): ").upper() != 'S':
            print("🚫 Importación cancelada.")
            return

        # 5. Concatenar con ingresos existentes y guardar
        df_ing_actualizado = pd.concat(
            [self.df_ing, df_filas], ignore_index=True
        )
        self._guardar(df_ing_actualizado, 'Ingresos')

        # 6. Actualizar df_ing en memoria para la sesión actual
        self.df_ing = self.repo.cargar_ingresos()
        print(f"\n🎉 ¡Inventario inicial importado exitosamente! ({len(df_filas)} registros)")

    # ── Helpers de UI ─────────────────────────

    def _pedir_tipo_movimiento(self) -> str | None:
        """Pide el tipo de movimiento con validación. Devuelve '1', '2', '3', '4' o None."""
        while True:
            print("\n1. INGRESO  |  2. SALIDA  |  3. CARGA INICIAL  |  4. CONSULTAR STOCK  |  C. Cancelar")
            tipo = input("Opción: ").strip().upper()
            if tipo == 'C':
                return None
            if tipo in ('1', '2', '3', '4'):
                return tipo
            print("❌ Opción inválida. Ingrese 1, 2, 3, 4 o C.")

    def _pedir_cantidad(self, maximo: float | None = None) -> float | None:
        """
        Pide una cantidad numérica positiva con hasta 3 reintentos.
        Si se indica 'maximo', valida que no lo supere.
        """
        for _ in range(3):
            try:
                cant = float(input("Cantidad: "))
                if cant <= 0:
                    print("❌ La cantidad debe ser mayor a 0.")
                    continue
                if maximo is not None and cant > maximo:
                    print(f"❌ Stock insuficiente. Máximo disponible: {maximo}")
                    continue
                return cant
            except ValueError:
                print("❌ Ingrese un número válido.")
        print("⚠️ Demasiados intentos fallidos. Registro cancelado.")
        return None

    @staticmethod
    def _parsear_fecha(texto: str):
        """Convierte string DD-MM-AAAA a datetime, o devuelve 'S/V'."""
        if not texto:
            return 'S/V'
        try:
            return datetime.strptime(texto, "%d-%m-%Y")
        except ValueError:
            print("⚠️ Formato de fecha inválido. Se guardará como 'S/V'.")
            return 'S/V'

    @staticmethod
    def _confirmar(nom: str, lote: str, cant: float) -> bool:
        """Pide confirmación antes de registrar."""
        print(f"\n¿Confirmar {cant} unidades de '{nom}' (Lote: {lote})?")
        return input("S/N: ").upper() == 'S'


# ═════════════════════════════════════════════
# PUNTO DE ENTRADA
# ═════════════════════════════════════════════

def main():
    drive.mount('/content/drive')

    repo     = InventarioRepo(RUTA_EXCEL)
    servicio = StockService(repo)
    menu     = MenuConsola(repo, servicio)

    menu.ejecutar()


if __name__ == '__main__':
    main()